name: "Build and Deploy to GH Pages"
on: 
  push:
    branches:
      - main

env:
  GODOT_VERSION: 4.3
  EXPORT_NAME: GmaeJamGame2024
  PROJECT_PATH: project

jobs:
  export-web:
    name: Web
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-20.04
    container:
      image: barichello/godot-ci:4.3
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true
      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/export_templates/
          mv /root/.local/share/godot/export_templates/${GODOT_VERSION}.stable ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable
      - name: Web Build
        run: |
          mkdir -v -p build/web
          cd $PROJECT_PATH
          godot --headless --verbose --export-release "Web" ../build/web/index.html
      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          name: github-pages
          path: build/web
      - name: GitHub Pages Deployment
        id: deployment
        uses: actions/deploy-pages@v4 
      - name: Itch.io deployment
        uses: KikimoraGames/itch-publish@v0.0.3
        with:
          butlerApiKey: ${{secrets.BUTLER_API_KEY}}
          gameData: ../build/web/index.html
          itchUsername: ${{env.ITCH_USERNAME}}
          itchGameId: gamejamgame2024
          buildChannel: 'html5'
      - name: Send Discord notification
        if: success()
        run: |
          apt-get update && apt-get install -y curl
          curl -X POST \
            -H "Content-Type: application/json" \
            -d "{\"content\": \"New version was deployed to GitHub Pages. Changes: ${{ github.event.head_commit.message }} - https://robliv.github.io/gamejam2024/\"}" \
            ${{ secrets.DISCORD_WEBHOOK_URL }}